"""Printable data-sanitisation certificate (HTML) for completed wipes."""
from __future__ import annotations

import getpass
import html
import platform
import time
import uuid

from .util import APP_NAME, APP_VERSION, human_size, human_time


def wipe_certificate(path: str, info: dict) -> str:
    """info keys: target, model, serial, size, bus, method, passes, verified, verify_mismatched_blocks,
    write_errors, start, end, scope"""
    cert_id = uuid.uuid4().hex[:12].upper()
    ok = info.get("write_errors", 0) == 0 and info.get("verify_mismatched_blocks", 0) == 0
    rows = [
        ("Certificate ID", cert_id),
        ("Result", "PASSED — data overwritten" + (" and verified" if info.get("verified") else "")
         if ok else "COMPLETED WITH ERRORS — see details"),
        ("Device", info.get("model") or "-"),
        ("Serial number", info.get("serial") or "-"),
        ("Interface", info.get("bus") or "-"),
        ("Capacity", human_size(info.get("size", 0))),
        ("Scope", info.get("scope", "-")),
        ("Target path", info.get("target", "-")),
        ("Method", info.get("method", "-")),
        ("Passes", str(info.get("passes", "-"))),
        ("Verification", "Read-back verified" if info.get("verified") else "Not verified"),
        ("Verify mismatches", str(info.get("verify_mismatched_blocks", 0))),
        ("Unwritable sectors", str(info.get("write_errors", 0))),
        ("Started", time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(info.get("start", time.time())))),
        ("Finished", time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(info.get("end", time.time())))),
        ("Duration", human_time(info.get("end", 0) - info.get("start", 0))),
        ("Operator", getpass.getuser()),
        ("Workstation", platform.node()),
        ("Software", f"{APP_NAME} {APP_VERSION}"),
    ]
    trs = "\n".join(f"<tr><th>{html.escape(k)}</th><td>{html.escape(str(v))}</td></tr>" for k, v in rows)
    badge = "#14A97A" if ok else "#E0284A"
    doc = f"""<!doctype html><html><head><meta charset="utf-8"><title>Data Erasure Certificate {cert_id}</title>
<style>
body{{font-family:Segoe UI,Arial,sans-serif;color:#1d1a2b;max-width:820px;margin:40px auto;padding:0 24px}}
h1{{font-size:26px;margin:0}} .sub{{color:#6e6884;margin:4px 0 24px}}
.badge{{display:inline-block;background:{badge};color:#fff;border-radius:20px;padding:6px 16px;font-weight:700}}
table{{width:100%;border-collapse:collapse;margin:24px 0}} th,td{{text-align:left;padding:9px 12px;
border-bottom:1px solid #e4e0ee;font-size:14px}} th{{width:34%;color:#6e6884;font-weight:600}}
.sig{{display:flex;gap:40px;margin-top:48px}} .sig div{{flex:1;border-top:1px solid #1d1a2b;padding-top:6px;
color:#6e6884;font-size:13px}} .note{{font-size:12px;color:#6e6884;margin-top:28px}}
@media print{{body{{margin:0}}}}
</style></head><body>
<h1>Certificate of Data Erasure</h1><div class="sub">Generated by {APP_NAME} {APP_VERSION}</div>
<span class="badge">{'PASSED' if ok else 'ERRORS'}</span>
<table>{trs}</table>
<div class="sig"><div>Technician signature</div><div>Date</div></div>
<p class="note">Overwrite-based erasure. For SSD/flash media, controller-level Secure Erase or Sanitize, or
physical destruction, is recommended in addition, as spare flash cells are not addressable by the host.</p>
</body></html>"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(doc)
    return cert_id
